export const SINGLE_PRODUCT_LOADING = 'SINGLE_PRODUCT_LOADING';
export const SINGLE_PRODUCT_ERROR = 'SINGLE_PRODUCT_ERROR';
export const SINGLE_PRODUCT_SUCCESS = 'SINGLE_PRODUCT_SUCCESS';
export const CREATE_PRODUCT_LOADING = 'CREATE_PRODUCT_LOADING';
export const CREATE_PRODUCT_ERROR = 'CREATE_PRODUCT_ERROR';
export const CREATE_PRODUCT_SUCESS = 'CREATE_PRODUCT_SUCESS';
